### ISSUE TITLE
添加拷贝漫画源

### ISSUE THREAD

**Issue by ChellyL** [hanerx/dcomic#34]
如题
拷贝漫画：https://www.copymanga.com/

**Comment by hanerx** [comment]
漫画内容需要使用app查看，但是我这抓包抓不到，需要有个人抓一下包

**Comment by hanerx** [comment]
问题解决，用user-agent欺骗就能获取所有内容

**Comment by ChellyL** [comment]
大佬牛逼！comic和tachiyomi都有这个源，可以借鉴吗

**Comment by hanerx** [comment]
api已经拉完了，其实没啥必要了

**Comment by hanerx** [comment]
已实现，等一个稳定性测试
