### ISSUE TITLE
动漫之家改接口了！

### ISSUE THREAD

**Issue by hanerx** [hanerx/dcomic#39]
**Bug现象简述**
大妈之家改了数据接口，v3接口全部报废

**复现方法**
无

**预期动作**
无

**截图**
无

**附加信息**
全部v4接口都是加密接口，完全看不懂的加密策略，已知不是base64、jwt、aes，但是完全不知道是啥加密策略，需要一个大手子解包

**Comment by Schezuk** [comment]
更新可以靠
https://m.dmzj.com/latest/0.json
或者
http://manhua.dmzj.com/update_1.shtml
先顶上
rank有
https://m.dmzj.com/rank/0-0-0-0.json
不过
https://m.dmzj.com/classify/${tag}-0-0-0-1-0.json
已经挂了

**Comment by Schezuk** [comment]
另外
关于分类，有一些分类不在分类页出现

完整的分类列表如下（分类本质是tag，其他的tag还有作者地域完结等等）
id="type_4" 	title="冒险"
id="type_5" 	title="欢乐向"
id="type_6" 	title="格斗"
id="type_7" 	title="科幻"
id="type_8" 	title="爱情"
id="type_9" 	title="侦探"
id="type_10"	title="竞技"
id="type_11"	title="魔法"
id="type_12"	title="神鬼"
id="type_13"	title="校园"
id="type_14"	title="惊悚"
id="type_16"	title="其他"
id="type_17"	title="四格"
id="type_3242" 	title="生活"
id="type_3243" 	title="ゆり"
id="type_3244" 	title="秀吉"
id="type_3245" 	title="悬疑"
id="type_3246" 	title="纯爱"
id="type_3248" 	title="热血"
id="type_3249" 	title="后宫"
id="type_3250" 	title="历史"
id="type_3251" 	title="战争"
id="type_3252" 	title="萌系"
id="type_3253" 	title="宅系"
id="type_3254" 	title="治愈"
id="type_3255" 	title="励志"
id="type_3324" 	title="武侠"
id="type_3325" 	title="机战"
id="type_3326" 	title="音乐舞蹈"
id="type_3327" 	title="美食"
id="type_3328" 	title="职场"
id="type_3365" 	title="西方魔幻"
id="type_4459" 	title="高清单行"
id="type_4518" 	title="性转换"
id="type_5077" 	title="东方"
id="type_5345" 	title="扶她"
id="type_5806" 	title="魔幻"
id="type_5848" 	title="奇幻"
id="type_6219" 	title="节操"
id="type_6316" 	title="轻小说"
id="type_6437" 	title="颜艺"
id="type_7568" 	title="搞笑"
id="type_7900" 	title="仙侠"
id="type_13627"	title="舰娘"
id="type_17192"	title="动画"
id="type_18522"	title="AA"

**Comment by Schezuk** [comment]
另外建议搞一个每章之间自动弹出评论页的设置项，否则按在官方客户端的习惯，翻到最后一页直接跳到下一章了

**Comment by Schezuk** [comment]
最后建议能识别专题列表，新漫专题已经到46期了，首页还是44。

**Comment by hanerx** [comment]
> 更新可以靠
> https://m.dmzj.com/latest/0.json
> 或者
> http://manhua.dmzj.com/update_1.shtml
> 先顶上
> rank有
> https://m.dmzj.com/rank/0-0-0-0.json
> 不过
> [https://m.dmzj.com/classify/${tag}-0-0-0-1-0.json](https://m.dmzj.com/classify/$%7Btag%7D-0-0-0-1-0.json)
> 已经挂了

已经改了，tag那个我是直接走的接口不是本地存的，专题估计是接口还是老接口，去看看能不能换

**Comment by hanerx** [comment]
> 另外
> 关于分类，有一些分类不在分类页出现
> 
> 完整的分类列表如下（分类本质是tag，其他的tag还有作者地域完结等等）
> id="type_4" title="冒险"
> id="type_5" title="欢乐向"
> id="type_6" title="格斗"
> id="type_7" title="科幻"
> id="type_8" title="爱情"
> id="type_9" title="侦探"
> id="type_10" title="竞技"
> id="type_11" title="魔法"
> id="type_12" title="神鬼"
> id="type_13" title="校园"
> id="type_14" title="惊悚"
> id="type_16" title="其他"
> id="type_17" title="四格"
> id="type_3242" title="生活"
> id="type_3243" title="ゆり"
> id="type_3244" title="秀吉"
> id="type_3245" title="悬疑"
> id="type_3246" title="纯爱"
> id="type_3248" title="热血"
> id="type_3249" title="后宫"
> id="type_3250" title="历史"
> id="type_3251" title="战争"
> id="type_3252" title="萌系"
> id="type_3253" title="宅系"
> id="type_3254" title="治愈"
> id="type_3255" title="励志"
> id="type_3324" title="武侠"
> id="type_3325" title="机战"
> id="type_3326" title="音乐舞蹈"
> id="type_3327" title="美食"
> id="type_3328" title="职场"
> id="type_3365" title="西方魔幻"
> id="type_4459" title="高清单行"
> id="type_4518" title="性转换"
> id="type_5077" title="东方"
> id="type_5345" title="扶她"
> id="type_5806" title="魔幻"
> id="type_5848" title="奇幻"
> id="type_6219" title="节操"
> id="type_6316" title="轻小说"
> id="type_6437" title="颜艺"
> id="type_7568" title="搞笑"
> id="type_7900" title="仙侠"
> id="type_13627" title="舰娘"
> id="type_17192" title="动画"
> id="type_18522" title="AA"

这个没法拿到图片，所以没法用
