### ISSUE TITLE
分类内容不全

### ISSUE THREAD

**Issue by hanerx** [hanerx/dcomic#40]
另外
关于分类，有一些分类不在分类页出现

完整的分类列表如下（分类本质是tag，其他的tag还有作者地域完结等等）
id="type_4" 	title="冒险"
id="type_5" 	title="欢乐向"
id="type_6" 	title="格斗"
id="type_7" 	title="科幻"
id="type_8" 	title="爱情"
id="type_9" 	title="侦探"
id="type_10"	title="竞技"
id="type_11"	title="魔法"
id="type_12"	title="神鬼"
id="type_13"	title="校园"
id="type_14"	title="惊悚"
id="type_16"	title="其他"
id="type_17"	title="四格"
id="type_3242" 	title="生活"
id="type_3243" 	title="ゆり"
id="type_3244" 	title="秀吉"
id="type_3245" 	title="悬疑"
id="type_3246" 	title="纯爱"
id="type_3248" 	title="热血"
id="type_3249" 	title="后宫"
id="type_3250" 	title="历史"
id="type_3251" 	title="战争"
id="type_3252" 	title="萌系"
id="type_3253" 	title="宅系"
id="type_3254" 	title="治愈"
id="type_3255" 	title="励志"
id="type_3324" 	title="武侠"
id="type_3325" 	title="机战"
id="type_3326" 	title="音乐舞蹈"
id="type_3327" 	title="美食"
id="type_3328" 	title="职场"
id="type_3365" 	title="西方魔幻"
id="type_4459" 	title="高清单行"
id="type_4518" 	title="性转换"
id="type_5077" 	title="东方"
id="type_5345" 	title="扶她"
id="type_5806" 	title="魔幻"
id="type_5848" 	title="奇幻"
id="type_6219" 	title="节操"
id="type_6316" 	title="轻小说"
id="type_6437" 	title="颜艺"
id="type_7568" 	title="搞笑"
id="type_7900" 	title="仙侠"
id="type_13627"	title="舰娘"
id="type_17192"	title="动画"
id="type_18522"	title="AA"

_Originally posted by @Schezuk in https://github.com/hanerx/dcomic/issues/39#issuecomment-826453529_

**Comment by hanerx** [comment]
这个没有图片啊，不能替换

**Comment by Schezuk** [comment]
> 这个没有图片啊，不能替换

有的，比如`http://v3api.dmzj.com/0/category.json`里现在没有百合，实际上图是做了的
https://images.dmzj1.com/tuijian/222_222/170811baihe.jpg

**Comment by hanerx** [comment]
这个我试的是170820的，都是挂掉的，而且里面还有一个日文的找不到数据

**Comment by hanerx** [comment]
![image](https://user-images.githubusercontent.com/31791623/116066755-f6392480-a6ba-11eb-9862-b950df53db38.png)
事实证明很多都是挂的

**Comment by hanerx** [comment]
![W W%)1DHGP4`L AM2@(K_NK](https://user-images.githubusercontent.com/31791623/116067601-df470200-a6bb-11eb-8bf4-5e33365580a8.jpg)好像前面那个是制作日期，那么问题来了，这个日期是多少

**Comment by Schezuk** [comment]
分类	原名				
	欢乐向		huanlexiang			
	惊悚		jingsong			
	其他		qita			
	生活		shenghuo			
	ゆり	百合	baihe	https://images.dmzj1.com/tuijian/222_222/170811baihe.jpg	百合	https://images.dmzj1.com/tuijian/222_222/baihe2.jpg
	纯爱	耽美	danmei	https://images.dmzj1.com/tuijian/222_222/170811danmei.jpg	耽美	https://images.dmzj1.com/tuijian/222_222/danmei.jpg
	泛爱	后宫	hougong	https://images.dmzj1.com/tuijian/222_222/170817hougong.jpg		
	TS	性转换/性转	xingzhuan	https://images.dmzj1.com/tuijian/222_222/170817xingzhuan.jpg		
	历史		lishi			
	战争		zhanzheng			
	宅系		zhaixi			
	武侠		wuxia			
	机战		jizhan			
	音乐舞蹈		yinyuewudao			
	西方魔幻		xifangmohuan			
	高清单行		gaoqingdanxing				
	扶她		futa				
	节操		jiecao			
	轻小说		qingxiaoshuo			
	动画		donghua			
	AA		AA				
	==========						
3262	少年漫			https://images.dmzj1.com/tuijian/222_222/180720shaonianman.jpg	少年	https://images.dmzj1.com/tuijian/222_222/kenan.jpg	
3263	少女漫			https://images.dmzj1.com/tuijian/222_222/180720shaonvman.jpg	少女	https://images.dmzj1.com/tuijian/222_222/yuanqi.jpg	
13626	女青漫			https://images.dmzj1.com/tuijian/222_222/180720nvqingman.jpg			
3264	青年漫			https://images.dmzj1.com/tuijian/222_222/180720qingnianman.jpg			
2308	国漫			https://images.dmzj1.com/tuijian/222_222/180720guoman.jpg	国漫	https://images.dmzj1.com/tuijian/222_222/mowang.jpg	
2305	韩国			https://images.dmzj1.com/tuijian/222_222/180720hanguo.jpg	韩国	https://images.dmzj1.com/tuijian/222_222/1112hanman.jpg	
2306	欧美			https://images.dmzj1.com/tuijian/222_222/180720oumei.jpg	欧美	https://images.dmzj1.com/tuijian/222_222/oumeimanh.jpg	
2304	日本			https://images.dmzj1.com/tuijian/222_222/180720riben.jpg	日本	https://images.dmzj1.com/tuijian/222_222/ribenmanhua.jpg	
2309	连载			https://images.dmzj1.com/tuijian/222_222/180720lianzai.jpg			
2310	完结			https://images.dmzj1.com/tuijian/222_222/180720wanjie.jpg	完结	https://images.dmzj1.com/tuijian/222_222/wanjie.jpg	
4	冒险			https://images.dmzj1.com/tuijian/222_222/180720maoxian.jpg	冒险	https://images.dmzj1.com/tuijian/222_222/maoxian.jpg
7900	仙侠			https://images.dmzj1.com/tuijian/222_222/170811xianxia.jpg	仙侠	https://images.dmzj1.com/tuijian/222_222/heibai.jpg
3244	秀吉	伪娘		https://images.dmzj1.com/tuijian/222_222/180803weiniang.jpg	伪娘	https://images.dmzj1.com/tuijian/222_222/akb49.jpg
13	校园			https://images.dmzj1.com/tuijian/222_222/170811xiaoyuan.jpg	校园	https://images.dmzj1.com/tuijian/222_222/xiaoyuan2.jpg
6	格斗			https://images.dmzj1.com/tuijian/222_222/170811gedou.jpg	格斗	https://images.dmzj1.com/tuijian/222_222/gedou.jpg
8	爱情	[神契]		https://images.dmzj1.com/tuijian/222_222/170811shenqi.jpg	爱情	https://images.dmzj1.com/tuijian/222_222/aiqing.jpg	
3245	悬疑	[恐怖]		https://images.dmzj1.com/tuijian/222_222/kongbu.jpg		
3327	美食			https://images.dmzj1.com/tuijian/222_222/170811meishi.jpg	美食	https://images.dmzj1.com/tuijian/222_222/meishi2.jpg
6316	轻小说改	[轻改]		https://images.dmzj1.com/tuijian/222_222/170811qinggai.jpg	轻小说改	https://images.dmzj1.com/tuijian/222_222/qingxiaoshuo2.jpg
4518	TS			https://images.dmzj1.com/tuijian/222_222/170817xingzhuan.jpg		
5806	魔幻			https://images.dmzj1.com/tuijian/222_222/170817mohuan.jpg		
3255	励志			https://images.dmzj1.com/tuijian/222_222/170817lizhi.jpg		
3254	治愈			https://images.dmzj1.com/tuijian/222_222/170817zhiyu.jpg		
3252	萌系			https://images.dmzj1.com/tuijian/222_222/170817mengxi.jpg		
3248	热血			https://images.dmzj1.com/tuijian/222_222/170817rexue.jpg		
17	四格			https://images.dmzj1.com/tuijian/222_222/170817sige.jpg		
12	神鬼			https://images.dmzj1.com/tuijian/222_222/170817shengui.jpg			
11	魔法			https://images.dmzj1.com/tuijian/222_222/170817mofa.jpg			
9	侦探			https://images.dmzj1.com/tuijian/222_222/170817zhentan.jpg			
7	科幻			https://images.dmzj1.com/tuijian/222_222/170817kehuan.jpg			
10	竞技			https://images.dmzj1.com/tuijian/222_222/170811jingji.jpg	竞技	https://images.dmzj1.com/tuijian/222_222/jingji.jpg	
5848	奇幻			https://images.dmzj1.com/tuijian/222_222/170811qihuan.jpg	奇幻	https://images.dmzj1.com/tuijian/222_222/qihuan.jpg	
6437	颜艺			https://images.dmzj1.com/tuijian/222_222/170811yanyi.jpg	颜艺	https://images.dmzj1.com/tuijian/222_222/1029luoxuanjuan.jpg	
7568	搞笑			https://images.dmzj1.com/tuijian/222_222/170811gaoxiao.jpg	搞笑	https://images.dmzj1.com/tuijian/222_222/gaoxiao2.jpg	
3328	职场			https://images.dmzj1.com/tuijian/222_222/170811zhichang.jpg	职场	https://images.dmzj1.com/tuijian/222_222/zhichang.jpg	
5077	东方			https://images.dmzj1.com/tuijian/222_222/170817dongfang.jpg	东方	https://images.dmzj1.com/tuijian/222_222/1029dongfang.jpg	
13627	舰娘			https://images.dmzj1.com/tuijian/222_222/170817jianniang.jpg			
	
	https://images.dmzj1.com/tuijian/222_222/170816nvqing.jpg
	https://images.dmzj1.com/tuijian/222_222/170811guoman.jpg
	https://images.dmzj1.com/tuijian/222_222/170811riben.jpg
	https://images.dmzj1.com/tuijian/222_222/170811hanguo.jpg
	https://images.dmzj1.com/tuijian/222_222/170811oumei.jpg
	https://images.dmzj1.com/tuijian/222_222/170811lianzai.jpg
	https://images.dmzj1.com/tuijian/222_222/170811wanjie.jpg
	https://images.dmzj1.com/tuijian/222_222/170811maoxian.jpg
	https://images.dmzj1.com/tuijian/222_222/170811weiniang.jpg
	
	https://images.dmzj1.com/tuijian/222_222/170811shaonvaqqing.jpg						
	https://images.dmzj1.com/tuijian/222_222/170811kehuan.jpg
	https://images.dmzj1.com/tuijian/222_222/170816qingnian.jpg

**Comment by Schezuk** [comment]
其实图片官方也常换，缺图片随便找点打包进安装包里就行

Category官方加的不勤，可以随版本号更新的，现在的主要问题是他隐藏一部分

**Comment by hanerx** [comment]
我打算以后做多源的如果不能云端获取的话那还是算了

**Comment by hanerx** [comment]
我拿软件爆破了一下，大部分都没有做图片，给个自己写json的功能开放给你们自己配置好了

**Comment by hanerx** [comment]
暂时改了一个凑合用的，就这样暂时用着好了

**Comment by hanerx** [comment]
![image](https://user-images.githubusercontent.com/31791623/116079420-5be0dd00-a6ca-11eb-937e-24c68db2f6d7.png)
改好了
