### ISSUE TITLE
建议搞一个每章之间自动弹出评论页的设置项

### ISSUE THREAD

**Issue by hanerx** [hanerx/dcomic#41]
另外建议搞一个每章之间自动弹出评论页的设置项，否则按在官方客户端的习惯，翻到最后一页直接跳到下一章了

_Originally posted by @Schezuk in https://github.com/hanerx/dcomic/issues/39#issuecomment-826457556_

**Comment by hanerx** [comment]
实现了

**Comment by Schezuk** [comment]
> 实现了
v1.4.10-beta.6
没有效果哇？重启了也不成。垂直水平翻页都是。

**Comment by hanerx** [comment]
侧边栏设置里有，默认不开启

**Comment by Schezuk** [comment]
> 侧边栏设置里有，默认不开启

我设过。无效。安卓版本9

**Comment by hanerx** [comment]
因为flutter懒加载的缘故，设置从数据库里加载到内存有延迟，每次重启后不能正常显示，需要等第二次进入阅读器的时候才会显示

**Comment by hanerx** [comment]
已修复
