### ISSUE TITLE
建议能识别专题列表

### ISSUE THREAD

**Issue by hanerx** [hanerx/dcomic#42]
最后建议能识别专题列表，新漫专题已经到46期了，首页还是44。

_Originally posted by @Schezuk in https://github.com/hanerx/dcomic/issues/39#issuecomment-826459690_

**Comment by hanerx** [comment]
直接加了一个专题列表，直接看专题列表好了

**Comment by Schezuk** [comment]
专题列表进去是灰色空白页
v1.4.10-beta.6

**Comment by hanerx** [comment]
单独开issue，给截图
