### ISSUE TITLE
专题页无效

### ISSUE THREAD

**Issue by Schezuk** [hanerx/dcomic#44]
![Screenshot_20210426_204246](https://user-images.githubusercontent.com/7524886/116084385-54bccd80-a6d0-11eb-9a1e-2a26705d639f.jpg)
单独开issue，给截图

_Originally posted by @hanerx in https://github.com/hanerx/dcomic/issues/42#issuecomment-826799214_

**Comment by hanerx** [comment]
后台debug数据还没传过来，不过盲猜一个没有登录，专题列表需要登录才能看到

**Comment by hanerx** [comment]
复现出来的是没有登录然后错误因为不是string格式的格式错误没成功捕获，改了应该能正常提示没登录需要登录了

**Comment by Schezuk** [comment]
> 后台debug数据还没传过来，不过盲猜一个没有登录，专题列表需要登录才能看到

官方客户端不需要登录。

**Comment by hanerx** [comment]
接口告诉我是要登陆的，估计官方还有第二个接口或者直接填的默认uid，但是我不知道默认uid那不如登录算了

**Comment by hanerx** [comment]
https://v3api.dmzj1.com/subject_with_level/0/0.json

```json
{
    "code": 666,
    "msg": "请先登录!",
    "data": []
}
```

**Comment by Schezuk** [comment]
https://m.dmzj1.com/subjectList.html

**Comment by hanerx** [comment]
写都写完了，等啥时候接口炸了再改了

**Comment by Schezuk** [comment]
> 写都写完了，等啥时候接口炸了再改了

开个webview然后接受专题页跳转怎么样

**Comment by hanerx** [comment]
拷贝漫画也有专题的，准备多接入不考虑使用webview，而且写webview开销大于写UI
