### ISSUE TITLE
Commic detail asynchronous suspension

### ISSUE THREAD

**Issue by Schezuk** [hanerx/dcomic#45]
**Bug现象简述**
默认源无效，无论开不开webapi，网页源正常。
尽管如此，`http://api.dmzj1.com/dynamic/comicinfo/4.json`浏览器可以正常访问
**复现方法**

**预期动作**

**截图**
![Screenshot_20210428_003931](https://user-images.githubusercontent.com/7524886/116279702-70040780-a7ba-11eb-9858-82f10649e05b.jpg)
控制台不支持复制和清空，很遗憾
**Smartphone (please complete the following information):**

**附加信息**
Webapi选项是干什么的的？

**Comment by hanerx** [comment]
webapi 用的网页端的api，动漫之家相关接口由于客户端迁移至v4，因此会逐步停止支持

**Comment by Schezuk** [comment]
> webapi 用的网页端的api，动漫之家相关接口由于客户端迁移至v4，因此会逐步停止支持
 但是明明v1 api可用还是打不开，v3却毫无问题……

**Comment by Schezuk** [comment]
还有一点，dmzj1.com的v3和dmzj.com的v3，隐藏行为是不一样的（前者隐藏的少）
