### ISSUE TITLE
1.4.14 版本号没改

### ISSUE THREAD

**Issue by SeanChengN** [hanerx/dcomic#47]
**Bug现象简述**
更新完成后重复提示更新，关于中还是1.4.13

**复现方法**
更新完成打开APP提示更新

**预期动作**

**截图**

**Smartphone (please complete the following information):**

**附加信息**
https://github.com/hanerx/dcomic/releases/tag/v1.4.14

**Comment by hanerx** [comment]
修好了，重新更新一下就行了
