### ISSUE TITLE
大妈之家混合源似乎失效了

### ISSUE THREAD

**Issue by ChellyL** [hanerx/dcomic#49]
**Bug现象简述**
可以看到首页和更新栏显示的漫画，但点击具体漫画后会提示“无法加载数据，可以尝试修改漫画源”

**复现方法**
随便点进一个漫画即可

**预期动作**
修复此问题（？）

**附加信息**
我问了xiaoyaocz大佬，他做的flutter版也出现类似情况，他让我把漫画源的“使用网页api”关闭，照做后问题解决。
但dcomic里关闭网页api似乎无效（

**Comment by hanerx** [comment]
因为这个一直用的网页的api，不过不知道为啥我这又好了，可能是服务器问题？

**Comment by hanerx** [comment]
我怀疑是大妈之家的问题，不过webapi那个东西确实不知道为啥不工作，到时候修修

**Comment by ChellyL** [comment]
还真是，我这儿也好了，估计是dmzj的问题

**Comment by hanerx** [comment]
DMZJ的源因为历史遗留问题有父类子类，然后我好像调用了俩的设置函数，导致父类应用了但是子类还是原来那个

**Comment by hanerx** [comment]
修好了
