### ISSUE TITLE
小红心

### ISSUE THREAD

**Issue by cool-delete** [hanerx/dcomic#50]
**Bug现象简述**
无法点击右上角的小红心

**复现方法**
1. 安装
2. 设置开启免登录
3. 点击到作品,观看后点右上角的小红心
4. 下面弹出 订阅中的黄色警告条(请先登录)

**预期动作**
逻辑不太适合 我已经可以免登录看漫画了 为什么记住漫画还是需要登录呢 这个功能也讲不通啊
希望能实现免登录的条件下仍然可以记录我看过的漫画

**Comment by cool-delete** [comment]
点错了 应该不算bug

**Comment by hanerx** [comment]
订阅调用的是每个漫画源实现的订阅功能，所以每个漫画源都有自己的处理逻辑，不登录订阅现在是不支持的

**Comment by cool-delete** [comment]
好的 明白了 谢谢
